**Data Extraction & Transformation (Python)**

**Step 1: Source data loaded from CSV**

In [1]:
import pandas as pd

# The original Google Drive link points to a viewer page, not the raw data.
# We need to convert it to a direct download link.
file_id = '19QzAIMQi3i4ggwWHXx325Y7aVIH3dyUx'
direct_download_url = f'https://drive.google.com/uc?export=download&id={file_id}'

df = pd.read_csv(direct_download_url)
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

**Data cleaning using Pandas---------------1.Duplicate Data removal**

In [2]:
#Total number of rows
total_rows = len(df)
print(total_rows)

# Count total duplicate rows
num_duplicates = df.duplicated().sum()
print(num_duplicates)

23193
35

In [3]:
# View the duplicate rows
duplicate_data = df[df.duplicated(keep=False)]
duplicate_data

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
1517,The Fisherman's Wharf,Yes,Yes,4.4/5,4099,080 49653108,Sarjapur Road,"Casual Dining, Bar","Sea Food, Caesar Salad, Jumbo Prawns, Cocktail...","Seafood, Goan, North Indian, Continental, Asian","1,400",Buffet,Bellandur
1532,The Fisherman's Wharf,Yes,Yes,4.4/5,4099,080 49653108,Sarjapur Road,"Casual Dining, Bar","Sea Food, Caesar Salad, Jumbo Prawns, Cocktail...","Seafood, Goan, North Indian, Continental, Asian","1,400",Buffet,Bellandur
1996,OPUS Club,No,Yes,4.4/5,1496,+91 8046444777\r\n+91 7349734900,Sarjapur Road,Pub,"Biryani, Cocktails, Nachos, Mocktails, Long Is...","Continental, Italian, North Indian, Mexican","1,900",Drinks & nightlife,Bellandur
1997,Float,Yes,Yes,4.4/5,3061,+91 9066887042\r\n+91 9066887086,Marathahalli,"Casual Dining, Bar","Butter Fish, Chicken Burritos, Cocktails, Mock...","North Indian, Japanese","1,500",Drinks & nightlife,Bellandur
1998,OPUS Club,No,Yes,4.4/5,1496,+91 8046444777\r\n+91 7349734900,Sarjapur Road,Pub,"Biryani, Cocktails, Nachos, Mocktails, Long Is...","Continental, Italian, North Indian, Mexican","1,900",Drinks & nightlife,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20784,BTDT? Been There Done That,No,Yes,4.3 /5,962,080 49652655,Indiranagar,"Bar, Casual Dining","Cocktails, Momos, Pizza, Mushroom Ragout, Roti...","European, Continental, Asian, Finger Food","1,300",Drinks & nightlife,Old Airport Road
20785,Tipsy Bull - The Bar Exchange,No,Yes,4.6 /5,3173,080 49652910,Indiranagar,"Bar, Casual Dining","Cocktails, Peri Peri Chicken, Biryani, Mocktai...","Chinese, Continental, North Indian, Mexican","1,400",Drinks & nightlife,Old Airport Road
20786,BTDT? Been There Done That,No,Yes,4.3 /5,962,080 49652655,Indiranagar,"Bar, Casual Dining","Cocktails, Momos, Pizza, Mushroom Ragout, Roti...","European, Continental, Asian, Finger Food","1,300",Drinks & nightlife,Old Airport Road
22001,ShakesBierre,No,Yes,4.4 /5,409,080 49653253,Brigade Road,"Microbrewery, Casual Dining","Cocktails, Mocktails, Pizza, Sweet Yogurt, Juj...","Asian, Continental, European, North Indian","1,500",Drinks & nightlife,Residency Road
22014,ShakesBierre,No,Yes,4.4 /5,409,080 49653253,Brigade Road,"Microbrewery, Casual Dining","Cocktails, Mocktails, Pizza, Sweet Yogurt, Juj...","Asian, Continental, European, North Indian","1,500",Drinks & nightlife,Residency Road

In [4]:
# View the duplicate rows sort by duplicated rows
duplicate_data = df[df.duplicated(keep=False)].sort_values(by=list(df.columns))
duplicate_data

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
13845,154 Breakfast Club,Yes,Yes,4.0 /5,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
13846,154 Breakfast Club,Yes,Yes,4.0 /5,1515,080 25533133,Koramangala 3rd Block,Cafe,"Pancakes, Waffles, Bbq Sandwich, Mushroom Rago...","Cafe, Continental",900,Dine-out,Koramangala 5th Block
5118,99 Pancakes,Yes,No,4.1/5,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
5417,99 Pancakes,Yes,No,4.1/5,41,+91 7483655827,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,Delivery,Church Street
19692,Alchemy - The Chancery Pavilion,No,Yes,4.3 /5,485,080 49653555,Residency Road,"Microbrewery, Casual Dining","Craft Beer, Cocktails, Stout, Chicken Wings, F...",Modern Indian,"2,000",Drinks & nightlife,MG Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8900,Toscano,Yes,Yes,4.5/5,715,080 22067757\r\n+91 7619320075,Koramangala 7th Block,Casual Dining,"Pizza, Pasta, Cocktails, Spinach Ravioli, Tira...","Italian, Salad","1,500",Delivery,Jayanagar
10761,Victoria Terminus,Yes,No,2.9/5,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
10763,Victoria Terminus,Yes,No,2.9/5,54,+91 9686933734\r\n+91 9066157771,Banaswadi,Quick Bites,"Vada Pav, Kulfi, Mumbai Sandwich, Rolls, Keema...","Fast Food, Maharashtrian, Rolls",250,Delivery,Kalyan Nagar
4238,Vyanjan,Yes,No,3.9/5,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM
4243,Vyanjan,Yes,No,3.9/5,201,+91 9916937446,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,Delivery,BTM

In [5]:
# Standard removal (returns a new DataFrame)
df_cleaned = df.drop_duplicates()

# Modify the existing DataFrame directly
df.drop_duplicates(inplace=True)
#Total number of rows after duplicates removal
total_rows = len(df)
print(total_rows)

23158

**Data cleaning using Pandas---------------2.Missing value handling**

In [6]:
# Returns a Series with the count of nulls for every column
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

**Data cleaning using Pandas---------------3.Rating Normalization**

In [7]:
# find out the unique data
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',
       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',
       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',
       '3.4/5', '2.7/5', '4.7/5', 'NEW', '2.4/5', '2.2/5', '2.3/5',
       '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5',
       '2.7 /5', '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5',
       '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5',
       '3.3 /5', '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5',
       '3.5 /5', '3.1 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [8]:
# removing the data from /
df['rate'] = df['rate'].str.split('/').str[0]
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [9]:
# removing the space from the column
df['rate'] = df['rate'].str.strip()
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [10]:
#turning errors like "NEW" or "-" into NaN
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [11]:
# find out the unique data
df['rate'].unique()

array([4.1, 3.8, 3.7, 4.6, 4. , 4.2, 3.9, 3. , 3.6, 2.8, 4.4, 3.1, 4.3,
       2.6, 3.3, 3.5, 3.2, 4.5, 2.5, 2.9, 3.4, 2.7, 4.7, nan, 2.4, 2.2,
       2.3, 4.8, 4.9, 2.1, 2. , 1.8])

In [12]:
# Convert the cleaned rating to a decimal number
df['rate'] = df['rate'].astype(float)
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [13]:
df.dtypes

name                            object
online_order                    object
book_table                      object
rate                           float64
votes                            int64
phone                           object
location                        object
rest_type                       object
dish_liked                      object
cuisines                        object
approx_cost(for two people)     object
listed_in(type)                 object
listed_in(city)                 object
dtype: object

In [14]:
from numpy import average
#Find Average Rating
average_rating = df['rate'].mean()
print(average_rating)
#

3.904002259690596

**Data cleaning using Pandas---------------4.Cost standardization**

In [15]:
# To modify the existing DataFrame directly (in-place)
df.rename(columns={'approx_cost(for two people)': 'cost'}, inplace=True)
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [16]:
#1. removing the comma to handle the numeric values
df['cost'] = df['cost'].str.replace(',', '')

# 2. Convert to numeric (coerce handles any weird strings by making them NaN)
df['cost'] = pd.to_numeric(df['cost'], errors='coerce')
df['cost']

0         800
1         800
2         800
3         300
4         600
         ...
23188    1200
23189    2000
23190    1200
23191     800
23192    2500
Name: cost, Length: 23158, dtype: int64

**Data cleaning using Pandas---------------5.Feature engineering for pricing segments and rating categories**

In [17]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

Data cleaning using Pandas---------------6.Cleaning

In [18]:
filtered_df = df[df['phone'].str.contains(r'\r|\n', na=False)]
filtered_df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
5,Timepass Dinner,Yes,No,3.8,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,Buffet,Banashankari
6,Onesta,Yes,Yes,4.6,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,Cafes,Banashankari
7,Penthouse Cafe,Yes,No,4.0,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,Cafes,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23183,BAR BAR,No,Yes,4.1,1003,+91 7338630404\n+91 8067266651,Whitefield,"Bar, Casual Dining","Mocktails, Cocktails, Pizza, Chicken Tikka, Na...","Continental, North Indian, Italian",1500,Pubs and bars,Whitefield
23186,Oliver's Pub & Diner,Yes,Yes,3.9,548,+91 8043691111\n+91 8028026519,Whitefield,"Pub, Casual Dining","Pizza, Beer, Cocktails, Nachos, Pasta, Moo Bur...","Finger Food, American, Continental, Burger, Pizza",1500,Pubs and bars,Whitefield
23187,Smaaash,No,Yes,4.0,189,+91 9900069474\n+91 7899644468,Whitefield,"Casual Dining, Pub","Pizza, Beer","North Indian, Pizza, Chinese",1500,Pubs and bars,Whitefield
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield

In [19]:
# Regex: find \r that is NOT followed by \n
lone_r_mask = df['phone'].str.contains(r'\r(?!\n)', regex=True, na=False)
df_lone_r = df[lone_r_mask]
df_lone_r

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
246,The Krishna Grand,Yes,No,3.9,888,080 26711192\r\r\r\r\n+91 7022268193,Banashankari,Casual Dining,"Spring Dosa, Coffee, Spring Roll, Masala Papad...","North Indian, South Indian, Chinese, Fast Food...",750,Dine-out,Banashankari
248,Mini Punjabi Dhaba,Yes,No,4.2,287,+91 9845044074\r\r\r\r\n+91 7406012344,Banashankari,Quick Bites,"Panneer Butter Masala, Lassi, Paratha, Jeera R...",North Indian,350,Dine-out,Banashankari
249,Onesta,Yes,Yes,4.6,2556,080 48653961\r\r\r\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,Dine-out,Banashankari
250,Wamama,Yes,Yes,4.2,354,+91 8042111599\r\r\r\r\n+91 8971818009,Banashankari,Casual Dining,"Sushi, Noodles, Wine, Khau Suey, Mocktails, Ya...","Asian, Korean, Indonesian, Japanese, Chinese, ...",800,Dine-out,Banashankari
251,Jalsa,Yes,Yes,4.1,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Dine-out,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12809,New Farm Fresh,No,No,3.6,34,+91 8884062000\r\r\n+91 8884632000,BTM,Quick Bites,Wood Fire Pizza,"Italian, Pizza",650,Dine-out,Koramangala 4th Block
12810,Khan Saheb Grills and Rolls,Yes,No,3.8,63,+91 9900743333\r\r\n+91 9900741111,Hosur Road,Quick Bites,"Rolls, Veggie Roll, Chicken Tikka Roll, Beda Roti","Fast Food, Rolls",350,Dine-out,Koramangala 4th Block
12812,Bamboo Heights,No,No,3.7,112,+91 9986094422\r\r\n+91 8105436214,BTM,Casual Dining,Friendly Staff,"Chinese, Fast Food, Continental",500,Dine-out,Koramangala 4th Block
12816,Chettayees,Yes,No,3.4,154,+91 9847632951\r\r\n+91 7259654051,BTM,Quick Bites,"Puttu Biryani, Egg Roast","Kerala, North Indian, Chinese",400,Dine-out,Koramangala 4th Block
12817,PSV's Andhra Paradise,Yes,No,3.5,117,080 65589315\r\r\n+91 8884077772,HSR,Casual Dining,"Chicken Guntur, Biryani, Thali","Andhra, Chinese, North Indian, Hyderabadi",600,Dine-out,Koramangala 4th Block

In [20]:
idx = df.columns.get_loc('phone')
print("Phone index is " + str(idx))

Phone index is 5

In [21]:
#phone number cleaning
#1. Add a alternative phone column after phone
df.insert(6, 'primary_phone', "")
df
#df['phone'] = df['phone'].str.split('\r\n').str[0]
#df

,name,online_order,book_table,rate,votes,phone,primary_phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [22]:
#phone number cleaning
#1. Add a alternative phone column after phone
df.insert(7, 'secondary_phone', "")
df
#df['phone'] = df['phone'].str.split('\r\n').str[0]
#df

,name,online_order,book_table,rate,votes,phone,primary_phone,secondary_phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,,,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,,,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,,,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,,,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,,,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,,,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,,,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,,,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,,,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,,,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [23]:
#1. search for the \r\n in the phone column data and split the data and store to 2 different columns
df[['primary_phone', 'secondary_phone']] = df['phone'].str.split('\r\n', expand=True)
df

,name,online_order,book_table,rate,votes,phone,primary_phone,secondary_phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,080 42297555,+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,080 41714161,None,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,+91 9663487993,None,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,+91 9620009302,None,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,+91 8026612447,+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,+91 7625087121\n+91 8050587483,None,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,080 49435000,None,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,080 39451000\n+91 8884038484,None,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,080 65951222,None,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,080 49652769,None,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [24]:
#2. search for the \n in the phone column data and split the data and store to 2 different columns
df[['primary_phone', 'secondary_phone']] = df['phone'].str.split('\n', expand=True)
df

,name,online_order,book_table,rate,votes,phone,primary_phone,secondary_phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,080 42297555\r,+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,080 41714161,None,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,+91 9663487993,None,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,+91 9620009302,None,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,+91 8026612447\r,+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,+91 7625087121,+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,080 49435000,None,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,080 39451000,+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,080 65951222,None,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,080 49652769,None,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [25]:
#1. removing the \r and \n to clean the phone number
df['primary_phone'] = df['primary_phone'].str.replace('\r', '')
df['primary_phone'] = df['primary_phone'].str.replace('\n', '')
df['secondary_phone'] = df['secondary_phone'].str.replace('\r', '')
df['secondary_phone'] = df['secondary_phone'].str.replace('\n', '')
df

,name,online_order,book_table,rate,votes,phone,primary_phone,secondary_phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,080 42297555,+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,080 41714161,None,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,+91 9663487993,None,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,+91 9620009302,None,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,+91 8026612447,+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,+91 7625087121,+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,080 49435000,080 49435000,None,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,080 39451000\n+91 8884038484,080 39451000,+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5,81,080 65951222,080 65951222,None,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,080 49652769,None,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [26]:
null_counts = df.isnull().sum()
print(null_counts)

name                   0
online_order           0
book_table             0
rate                 146
votes                  0
phone                  0
primary_phone          0
secondary_phone    11331
location               0
rest_type              0
dish_liked             0
cuisines               0
cost                   0
listed_in(type)        0
listed_in(city)        0
dtype: int64

In [27]:
filtered_df = df[df['location'].str.contains(r',', na=False)]
filtered_df

,name,online_order,book_table,rate,votes,phone,primary_phone,secondary_phone,location,rest_type,dish_liked,cuisines,cost,listed_in(type),listed_in(city)
3018,Cafe Thulp,Yes,No,3.4,54,+91 8892894103\r\n+91 7204273213,+91 8892894103,+91 7204273213,"ITPL Main Road, Whitefield",Cafe,"Burgers, Pasta Alfredo, Pork Burger, Pizza","Cafe, Burger, Italian, Salad",1000,Cafes,Brookefield
3024,Empire Restaurant,Yes,No,3.5,156,080 43334321\r\n+91 9916767287,080 43334321,+91 9916767287,"Varthur Main Road, Whitefield","Takeaway, Delivery","Roti, Shawarma, Tandoori Chicken, Paratha, Egg...","Kerala, Seafood, South Indian, Chinese, North ...",400,Delivery,Brookefield
3029,Fish Chain,Yes,No,3.8,78,+91 7676564444,+91 7676564444,None,"Varthur Main Road, Whitefield","Takeaway, Delivery",Biryani,"Seafood, BBQ, Biryani",250,Delivery,Brookefield
3032,Techies Kitchen,Yes,No,3.6,193,+91 9880329528,+91 9880329528,None,"ITPL Main Road, Whitefield",Delivery,"Chicken Biryani, Aloo Paratha","Biryani, North Indian",400,Delivery,Brookefield
3044,Mojo Pizza - 2X Toppings,Yes,No,4.3,200,022 33252828,022 33252828,None,"ITPL Main Road, Whitefield","Takeaway, Delivery","Chicken Wings, Garlic Bread, Cheesy Pizza, Cho...",Pizza,600,Delivery,Brookefield
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23132,Breakfast House,No,No,3.6,49,080 28413047\n+91 9900020540,080 28413047,+91 9900020540,"ITPL Main Road, Whitefield",Quick Bites,"Coffee, Vada, Mla Dosa","South Indian, North Indian",300,Dine-out,Whitefield
23133,Hottey Smokey,Yes,No,3.8,83,+91 7019919639,+91 7019919639,None,"ITPL Main Road, Whitefield",Food Court,"Chicken Shashlik, Pasta, Veg Sizzler","Continental, Fast Food",500,Dine-out,Whitefield
23134,Fujian Express,Yes,No,3.8,182,+91 7760075458\n+91 9591852291,+91 7760075458,+91 9591852291,"ITPL Main Road, Whitefield",Food Court,"Noodles, Chicken Noodle, Momos, American Chops...","Thai, Chinese, Momos",600,Dine-out,Whitefield
23164,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,080 49652769,None,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Drinks & nightlife,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,080 49652769,080 49652769,None,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs and bars,Whitefield

In [28]:
# import sqlite3

# # 1. Connect to a database (creates it if it doesn't exist)
# conn = sqlite3.connect('UberEats.db')

# # 2. Create a cursor object to execute commands
# cursor = conn.cursor()

# # This creates the table 'new_table' automatically from your df
# df.to_sql('restaurant', conn, if_exists='replace', index=False)

# # 6. Fetch and display data
# cursor.execute('SELECT * FROM restaurant')
# rows = cursor.fetchall()
# for row in rows:
#     print(row)

# # 7. Close the connection when finished
# conn.close()

In [29]:
# import sqlite3
# import pandas as pd

# with sqlite3.connect('UberEats.db') as conn:
#     # This single line handles the query AND the formatting
#     dfsql = pd.read_sql_query("SELECT * FROM restaurant", conn)
#     display(dfsql)

In [30]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.6.0)

In [31]:
import mysql.connector

connection = mysql.connector.connect(
        host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
        port = 4000,
        user = "3CpXt5wbBX6bRW8.root",
        password = "HG4kANh3M9JbzthS",
        database = "DEMO" # Optional: The database you want to use
    )

cursor = connection.cursor()
cursor.execute("SELECT DATABASE();")
record = cursor.fetchone()
print(f"You're connected to: {record}")

You're connected to: ('DEMO',)

In [32]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [33]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine('mysql+mysqlconnector://3CpXt5wbBX6bRW8.root:HG4kANh3M9JbzthS@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/UberEats')

df.to_sql(name='restuarant', con=engine, if_exists='replace', index=False)

-1

In [ ]:
# import pandas as pd
# from sqlalchemy import create_engine

# # 2. Define your SELECT query
# sql_query = "SELECT * FROM ubereats.restuarant WHERE online_order = 'Yes' LIMIT 100"

# # 3. Fetch data into a DataFrame
# mysqldf = pd.read_sql(sql_query, con=engine)

# # 4. Preview the data
# display(mysqldf)

**Key Business Questions Answered (Any 10 Questions)**

1.	Which Bangalore locations have the highest average restaurant ratings?
 Business Value: Identifies premium-performing areas suitable for brand positioning and new partner onboarding.

In [35]:
# import pandas as pd
# from sqlalchemy import create_engine

# # 2. Define your SELECT query
# sql_query = "SELECT location , avg(rate)as avgrate FROM `UberEats`.`restuarant`  group by location ORDER by avgrate desc"

# # 3. Fetch data into a DataFrame
# mysqldf = pd.read_sql(sql_query, con=engine)

# # 4. Preview the data
# display(mysqldf)

                 location   avgrate
0            Lavelle Road  4.192534
1   Koramangala 5th Block  4.151507
2             Sankey Road  4.105882
3   Koramangala 3rd Block  4.101242
4         Cunningham Road  4.100300
..                    ...       ...
83        Kanakapura Road  3.400000
84        South Bangalore  3.384211
85         West Bangalore  3.300000
86        Old Madras Road  3.137500
87           Bommanahalli  3.135714

[88 rows x 2 columns]

In [36]:
! pip install tabulate mysql-connector-python

Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.6.0)

In [37]:
import mysql.connector
from tabulate import tabulate
# Replace with your actual credentials
connection = mysql.connector.connect(
        host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
        port = 4000,
        user = "3CpXt5wbBX6bRW8.root",
        password = "HG4kANh3M9JbzthS",
        database = "UberEats" # Optional: The database you want to use
    )
cursor = connection.cursor()

In [38]:


cursor.execute("SELECT location , avg(rate)as avgrate FROM `UberEats`.`restuarant`  group by location ORDER by avgrate desc")



from tabulate import tabulate
headers = [i[0] for i in cursor.description]
print(tabulate(cursor.fetchall(), headers=headers, tablefmt="psql"))

+-------------------------------+-----------+
| location                      |   avgrate |
|-------------------------------+-----------|
| Lavelle Road                  |   4.19253 |
| Koramangala 5th Block         |   4.15151 |
| Sankey Road                   |   4.10588 |
| Koramangala 3rd Block         |   4.10124 |
| Cunningham Road               |   4.1003  |
| St. Marks Road                |   4.09901 |
| Koramangala 2nd Block         |   4.07333 |
| Sadashiv Nagar                |   4.05526 |
| Residency Road                |   4.05136 |
| Church Street                 |   4.04545 |
| Koramangala 4th Block         |   4.04415 |
| Seshadripuram                 |   4.03188 |
| Richmond Road                 |   4.02906 |
| Ulsoor                        |   4.02119 |
| Koramangala                   |   4.01176 |
| Koramangala 7th Block         |   3.98755 |
| Race Course Road              |   3.98667 |
| Hosur Road                    |   3.98333 |
| Malleshwaram                  |   3.96612 |
| Koramangala 8th Block         |   3.96148 |
| Indiranagar                   |   3.96146 |
| Hennur                        |   3.95294 |
| MG Road                       |   3.95025 |
| Vasanth Nagar                 |   3.95    |
| Koramangala 6th Block         |   3.94721 |
| Brigade Road                  |   3.94496 |
| HBR Layout                    |   3.94286 |
| Kalyan Nagar                  |   3.9357  |
| Jayanagar                     |   3.93505 |
| City Market                   |   3.92857 |
| Shivajinagar                  |   3.90145 |
| Langford Town                 |   3.9     |
| Yelahanka                     |   3.9     |
| Magadi Road                   |   3.9     |
| Sanjay Nagar                  |   3.9     |
| Sarjapur Road                 |   3.89356 |
| Majestic                      |   3.88889 |
| Infantry Road                 |   3.8883  |
| Kammanahalli                  |   3.87977 |
| Koramangala 1st Block         |   3.87489 |
| Rajajinagar                   |   3.86115 |
| New BEL Road                  |   3.8571  |
| JP Nagar                      |   3.85167 |
| Rajarajeshwari Nagar          |   3.85    |
| Vijay Nagar                   |   3.84    |
| HSR                           |   3.83873 |
| Basavanagudi                  |   3.83671 |
| Basaveshwara Nagar            |   3.82394 |
| Thippasandra                  |   3.82093 |
| Whitefield                    |   3.81815 |
| Wilson Garden                 |   3.81707 |
| Banashankari                  |   3.81344 |
| Old Airport Road              |   3.81188 |
| Frazer Town                   |   3.79659 |
| Yeshwantpur                   |   3.775   |
| Sahakara Nagar                |   3.775   |
| BTM                           |   3.7572  |
| Mysore Road                   |   3.75    |
| Ejipura                       |   3.74828 |
| Marathahalli                  |   3.73392 |
| Brookefield                   |   3.69935 |
| Electronic City               |   3.69625 |
| Commercial Street             |   3.69291 |
| Domlur                        |   3.68641 |
| Bellandur                     |   3.68453 |
| Jeevan Bhima Nagar            |   3.68391 |
| Bannerghatta Road             |   3.68226 |
| Nagawara                      |   3.66774 |
| Shanti Nagar                  |   3.65723 |
| Varthur Main Road, Whitefield |   3.65556 |
| ITPL Main Road, Whitefield    |   3.64762 |
| Banaswadi                     |   3.64103 |
| Jalahalli                     |   3.63333 |
| CV Raman Nagar                |   3.62857 |
| Kumaraswamy Layout            |   3.62321 |
| RT Nagar                      |   3.61364 |
| KR Puram                      |   3.6     |
| Central Bangalore             |   3.6     |
| North Bangalore               |   3.6     |
| Uttarahalli                   |   3.575   |
| Kaggadasapura                 |   3.56458 |
| East Bangalore                |   3.5125  |
| Rammurthy Nagar               |   3.43333 |
| Kanakapura Road               |   3.4     |
| South Bangalore               |   3.38421 |
| West Bangalore                |   3.3     |
| Old Madras Road               |   3.1375  |
| Bommanahalli                  |   3.13571 |
+-------------------------------+-----------+